package org.powbot.krulvis.fighter

const val WARRIOR_GUILD_OPTION = "Warrior Guild"
const val RADIUS_OPTION = "Kill Radius"
const val INVENTORY_OPTION = "Inventory"
const val EQUIPMENT_OPTION = "Equipment"
const val MONSTERS_OPTION = "Monsters"
const val HOP_FROM_PLAYERS_OPTION = "Hop From Players"
const val PLAYER_HOP_COUNT_OPTION = "Player Count"
const val USE_SAFESPOT_OPTION = "Use Safespot"
const val WAIT_FOR_LOOT_OPTION = "Wait For Loot"
const val WALK_BACK_TO_SAFESPOT_OPTION = "Walk Back"
const val CENTER_TILE_OPTION = "Safespot Center"
const val IRONMAN_DROPS_OPTION = "Ironman Drops"
const val LOOT_PRICE_OPTION = "Min Loot Price"
const val LOOT_OVERRIDES_OPTION = "Loot Overrides"
const val BURY_BONES_OPTION = "Bury Bones"
const val BANK_TELEPORT_OPTION = "Bank Teleport"
const val MONSTER_TELEPORT_OPTION = "Monster Teleport"
const val MONSTER_AUTO_DESTROY_OPTION = "Auto Kill"
