package org.powbot.krulvis.tithe;

import org.jetbrains.annotations.NotNull;
import org.powbot.krulvis.api.gui.ATGUI;
import org.powbot.krulvis.api.utils.resources.ATGson;
import z.P;

import javax.swing.*;
import java.awt.*;

public class TitheGUI extends ATGUI<TitheFarmer, TitheProfile> {
    private JPanel rootPanel;
    private JPanel optionPanel;
    private JSlider patchCountSlider;
    private JLabel patchCountLabel;

    public TitheGUI(@NotNull TitheFarmer script) {
        super(script);
        patchCountSlider.addChangeListener((e) -> {
            patchCountLabel.setText("Patch count: " + patchCountSlider.getValue());
        });
        initialize(rootPanel);
    }

    @Override
    public void onStart(@NotNull TitheFarmer script, @NotNull TitheProfile settings) {
        script.setProfile(settings);
        script.setStarted(true);
    }

    @NotNull
    @Override
    public TitheProfile getCurrentSettings() {
        return new TitheProfile(patchCountSlider.getValue());
    }

    @Override
    public void loadSettings(@NotNull TitheProfile settings) {
        patchCountSlider.setValue(settings.getPatchCount());
    }

    @NotNull
    @Override
    public TitheProfile parseSettings(@NotNull String inputText) {
        return ATGson.INSTANCE.Gson().fromJson(inputText, TitheProfile.class);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new GridBagLayout());
        optionPanel = new JPanel();
        optionPanel.setLayout(new GridBagLayout());
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.BOTH;
        rootPanel.add(optionPanel, gbc);
        patchCountSlider = new JSlider();
        patchCountSlider.setMaximum(16);
        patchCountSlider.setMinimum(8);
        patchCountSlider.setMinorTickSpacing(1);
        patchCountSlider.setPaintLabels(true);
        patchCountSlider.setPaintTicks(true);
        patchCountSlider.setPaintTrack(true);
        patchCountSlider.setSnapToTicks(false);
        patchCountSlider.setValue(10);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        optionPanel.add(patchCountSlider, gbc);
        patchCountLabel = new JLabel();
        patchCountLabel.setText("Patch count: 10");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        optionPanel.add(patchCountLabel, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }

}
