package org.powbot.krulvis.vorkath

object Data {

	val lootNames = arrayOf(
		"clue scroll",
		"brimstone key",
		"scaly blue dragonhide",
		"dragonbone necklace",
		"jar of decay",
		"draconic visage",
		"skeletal visage",
		"nature rune",
		"rune battleaxe",
		"loop half of key",
		"tooth half of key",
		"law rune",
		"death rune",
		"chaos rune",
		"wrath rune",
		"rune sq shield",
		"dragonstone",
		"rune kiteshield",
		"dragon med helm",
		"shield left half",
		"dragon spear",
		"coins",
		"grapes",
		"adamantite ore",
		"magic logs",
		"manta ray",
		"dragon bones",
		"diamond",
		"snapdragon seed",
		"torstol seed",
		"ranarr seed",
		"mahogany seed",
		"teak seed",
		"yew seed",
		"magic seed",
		"spirit seed",
		"dragonfruit tree seed",
		"celastrus seed",
		"redwood tree seed",
		"superior dragon bones",
		"rune longsword",
		"battlestaff",
		"dragon battleaxe",
		"dragon longsword",
		"dragon platelegs",
		"dragon plateskirt",
		"blue dragonhide",
		"green dragonhide",
		"red dragonhide",
		"black dragonhide",
		"dragon bolts (unf)",
		"dragon dart tip",
		"dragonstone bolt tip",
		"onyx bolt tip",
		"rune dart tip",
		"dragon arrowtip",
		"diamond bolt tip",
		"emerald bolt tip",
		"ruby bolt tip",
		"dragonstone bolt tip",
		"sapphire bolt tip",
		"onyx bolt tip"
	)
}